// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbFndNsUajmW8T2hy-6NmxOU1SAUT6IVg',
    appId: '1:275454654281:web:19468289c0c40b56dc8c98',
    messagingSenderId: '275454654281',
    projectId: 'money-manager-4b74c',
    authDomain: 'money-manager-4b74c.firebaseapp.com',
    storageBucket: 'money-manager-4b74c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASjIZHTaMBiXgyNa7R0l741HaWu4gGQ1c',
    appId: '1:275454654281:android:a46d8bb593baa104dc8c98',
    messagingSenderId: '275454654281',
    projectId: 'money-manager-4b74c',
    storageBucket: 'money-manager-4b74c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJR6N0XPegoYIWo8upm1RdcouXIl9qXmo',
    appId: '1:275454654281:ios:059f3beb2cf71b80dc8c98',
    messagingSenderId: '275454654281',
    projectId: 'money-manager-4b74c',
    storageBucket: 'money-manager-4b74c.appspot.com',
    iosBundleId: 'com.example.quizMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJR6N0XPegoYIWo8upm1RdcouXIl9qXmo',
    appId: '1:275454654281:ios:059f3beb2cf71b80dc8c98',
    messagingSenderId: '275454654281',
    projectId: 'money-manager-4b74c',
    storageBucket: 'money-manager-4b74c.appspot.com',
    iosBundleId: 'com.example.quizMoneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbFndNsUajmW8T2hy-6NmxOU1SAUT6IVg',
    appId: '1:275454654281:web:6e4e41cddef962f7dc8c98',
    messagingSenderId: '275454654281',
    projectId: 'money-manager-4b74c',
    authDomain: 'money-manager-4b74c.firebaseapp.com',
    storageBucket: 'money-manager-4b74c.appspot.com',
  );
}
